extraction:
  cpp:
    prepare:
      packages:
        - libboost-all-dev
        - libopenmpi-dev
        - libxml2-dev
        - libeigen3-dev
        - python-dev
        - python-numpy
    configure:
      command:
        - cmake -DPRECICE_PETScMapping=OFF .
