extraction:
  cpp:
    prepare:
      packages:
        - petsc-dev
        - libboost-all-dev
        - libopenmpi-dev
        - libxml2-dev
        - libeigen3-dev
        - python-dev
        - python-numpy
