repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v8.0.1'
  hooks:
  - id: clang-format
    exclude: "^thirdparty"
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: check-xml
  - id: check-merge-conflict
  - id: mixed-line-ending
- repo: https://github.com/precice/precice-pre-commit-hooks
  rev: 'v2.1'
  hooks:
  - id: format-precice-config
