language: cpp

compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-4.8
      - python-numpy
      - openmpi-bin
      - libopenmpi-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-log1.55-dev
env:
  global:
    - CPLUS_INCLUDE_PATH="$HOME/eigen-eigen-bdd17ee3b1b3"
  matrix:
    - MPI=off
    - MPI=on

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - export OMPI_CXX=$CXX
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi

install:
  - wget http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2 -O - | tar xj -C $HOME

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - scons -j 2 boost_inst=on petsc=off mpi=$MPI python=on compiler=$CXX
  - cd tests
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-test-config.xml ../src; fi
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-integration-test-config.xml ../src; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-test-config.xml ../src; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-integration-test-config.xml ../src; fi

  
after_failure:
  - cat config.log
