name: clang-tidy
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'cmake/**'
      - 'examples/**'
      - 'src/**'
      - 'thirdparty/**'
      - '.github/workflows/clang-tidy.yml'
  workflow_dispatch:

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container: 'precice/ci-ubuntu-2204:latest'
    steps:
      - uses: actions/checkout@v2
      - name: fetch clang
        run: apt update && apt install -y clang && apt install -y clang-tidy
      - name: run clang-tidy
        run: tools/formatting/run_clang_tidy.sh
