name: Develop image
# Builds the nightly precice/precice:develop image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  dockerfile:
    name: "Develop docker "
    runs-on: ubuntu-latest
    env:
        docker_username: precice
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: true
          file: "./tools/releasing/packaging/develop/Dockerfile"
          tags: ${{ env.docker_username }}/precice:develop
