name: "Release Dockerfile"
on:
  release:
    types: released
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: precice
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v2
        env:
          version: ${{ github.event.release.tag_name }}
        with:
          push: true
          file: "./tools/releasing/packaging/docker/Dockerfile"
          tags: precice/precice:${{ env.version }},precice/precice:latest
          build-args: |
            version=${{ env.version }}
