name: System tests

on:
  pull_request:
    types: [labeled]

jobs:
  gather-refs:
    name: Map Git branches to latest refs
    if: ${{ github.event.label.name == 'trigger-system-tests' }}
    runs-on: ubuntu-latest
    outputs:
      ref-python-bindings: ${{ steps.ref-python-bindings.outputs.shorthash }}
      ref-calculix-adapter: ${{ steps.ref-calculix-adapter.outputs.shorthash }}
      ref-fenics-adapter: ${{ steps.ref-fenics-adapter.outputs.shorthash }}
      ref-openfoam-adapter: ${{ steps.ref-openfoam-adapter.outputs.shorthash }}
      ref-su2-adapter: ${{ steps.ref-su2-adapter.outputs.shorthash }}
      ref-tutorials: ${{ steps.ref-tutorials.outputs.shorthash }}
    steps:
      - id: ref-python-bindings
        name: Get Python bindings ref
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: precice
          repo: python-bindings
          branch: develop
      - id: ref-calculix-adapter
        name: Get CalculiX adapter ref
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: precice
          repo: calculix-adapter
          branch: develop
      - id: ref-fenics-adapter
        name: Get FEniCS adapter ref
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: precice
          repo: fenics-adapter
          branch: develop
      - id: ref-openfoam-adapter
        name: Get OpenFOAM adapter ref
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: precice
          repo: openfoam-adapter
          branch: develop
      - id: ref-su2-adapter
        name: Get SU2 adapter ref
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: precice
          repo: su2-adapter
          branch: develop
      - id: ref-tutorials
        name: Get tutorials ref
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          owner: precice
          repo: tutorials
          branch: develop
      - id: report-refs
        name: Report Git refs
        run: |
          echo "Python bindings:" ${{ steps.ref-python-bindings.outputs.shorthash }} ${{ steps.ref-python-bindings.outputs.description }}
          echo "CalculiX adapter:" ${{ steps.ref-calculix-adapter.outputs.shorthash }} ${{ steps.ref-calculix-adapter.outputs.description }}
          echo "FEniCS adapter:" ${{ steps.ref-fenics-adapter.outputs.shorthash }} ${{ steps.ref-fenics-adapter.outputs.description }}
          echo "OpenFOAM adapter:" ${{ steps.ref-openfoam-adapter.outputs.shorthash }} ${{ steps.ref-openfoam-adapter.outputs.description }}
          echo "SU2 adapter:" ${{ steps.ref-su2-adapter.outputs.shorthash }} ${{ steps.ref-su2-adapter.outputs.description }}
          echo "Tutorials:" ${{ steps.ref-tutorials.outputs.shorthash }} ${{ steps.ref-tutorials.outputs.description }}

  run-system-tests:
    name: Trigger system tests
    if: ${{ github.event.label.name == 'trigger-system-tests' }}
    needs: gather-refs
    uses: precice/tutorials/.github/workflows/run_testsuite_workflow.yml@develop
    with:
      suites: release_test
      build_args: "PLATFORM:ubuntu_2204,
        PRECICE_REF:${{ github.event.pull_request.head.sha }},
        PYTHON_BINDINGS_REF:${{ needs.gather-refs.outputs.ref-python-bindings }},
        OPENFOAM_EXECUTABLE:openfoam2406,
        OPENFOAM_ADAPTER_REF:${{ needs.gather-refs.outputs.ref-openfoam-adapter }},
        FENICS_ADAPTER_REF:${{ needs.gather-refs.outputs.ref-fenics-adapter }},
        CALCULIX_VERSION:2.20,
        CALCULIX_ADAPTER_REF:${{ needs.gather-refs.outputs.ref-calculix-adapter }},
        SU2_VERSION:7.5.1,
        SU2_ADAPTER_REF:${{ needs.gather-refs.outputs.ref-su2-adapter }},
        TUTORIALS_REF:${{ needs.gather-refs.outputs.ref-tutorials }}"
      systests_branch: develop
      loglevel: "DEBUG"
